// <auto-generated />
using System;
using EF10_InventoryDBLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF10_InventoryDBLibrary.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250804040258_update-value-again")]
    partial class updatevalueagain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.6.25358.103")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF10_InventoryModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Movie",
                            Description = "Film or motion picture",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Book",
                            Description = "Printed or written literary work",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Game",
                            Description = "Interactive entertainment",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Toy/Collectable",
                            Description = "Physical toy or collectible",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EF10_InventoryModels.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContributorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("ContributorName")
                        .IsUnique();

                    b.ToTable("Contributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributorName = "Harrison Ford",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ContributorName = "Carrie Fisher",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ContributorName = "George Lucas",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            ContributorName = "John Williams",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            ContributorName = "J.R.R. Tolkien",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            ContributorName = "Wargaming",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            ContributorName = "Hallmark",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            ContributorName = "Christian Bale",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            ContributorName = "Katie Holmes",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            ContributorName = "Christopher Nolan",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            ContributorName = "Hans Zimmer",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            ContributorName = "James Newton Howard",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            ContributorName = "Frank Herbert",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            ContributorName = "Denis Villeneuve",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            ContributorName = "Timothée Chalamet",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            ContributorName = "Zendaya",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            ContributorName = "J.K. Rowling",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            ContributorName = "Daniel Radcliffe",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            ContributorName = "Chris Columbus",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            ContributorName = "Blizzard Entertainment",
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            ContributorName = "Stephen King",
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            ContributorName = "Stanley Kubrick",
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            ContributorName = "Jack Nicholson",
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            ContributorName = "Funko",
                            IsActive = true
                        },
                        new
                        {
                            Id = 25,
                            ContributorName = "Rockstar Games",
                            IsActive = true
                        },
                        new
                        {
                            Id = 26,
                            ContributorName = "Agatha Christie",
                            IsActive = true
                        },
                        new
                        {
                            Id = 27,
                            ContributorName = "Kenneth Branagh",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EF10_InventoryModels.DTOs.ContributorSummaryDTO", b =>
                {
                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<string>("ContributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemTitles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vwContributorsItems", (string)null);
                });

            modelBuilder.Entity("EF10_InventoryModels.DTOs.ItemByCategoryDTO", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("ItemsByCategory", (string)null);
                });

            modelBuilder.Entity("EF10_InventoryModels.DTOs.ItemByGenreDTO", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("ItemsByGenre", (string)null);
                });

            modelBuilder.Entity("EF10_InventoryModels.DTOs.ItemDetailSummaryDTO", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contributors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vwItemsWithGenresAndContributors", (string)null);
                });

            modelBuilder.Entity("EF10_InventoryModels.DTOs.ItemWithCsvDetailsDTO", b =>
                {
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorsCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenresCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("EF10_InventoryModels.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("GenreName")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Science Fiction",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Fantasy",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Adventure",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "Classic",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            GenreName = "Thriller",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            GenreName = "Horror",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            GenreName = "Mystery",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            GenreName = "Action",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            GenreName = "Drama",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            GenreName = "Superhero",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            GenreName = "Collectible",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EF10_InventoryModels.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOnSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchasedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique();

                    b.ToTable("Items", t =>
                        {
                            t.HasCheckConstraint("CK_Item_CurrentValue_NonNegative", "[CurrentValue] IS NULL OR [CurrentValue] >= 0");

                            t.HasCheckConstraint("CK_Item_PurchasePrice_NonNegative", "[PurchasePrice] IS NULL OR [PurchasePrice] >= 0");

                            t.HasCheckConstraint("CK_Item_Quantity_NonNegative", "[Quantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The original Star Wars movie.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Star Wars: A New Hope",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic fantasy novel by J.R.R. Tolkien.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Popular online multiplayer tank game.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "World of Tanks",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Collectible Hallmark ornament.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Star Trek™: U.S.S. Enterprise: NCC-1701 Ornament",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Christopher Nolan's Batman movie.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Batman Begins",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Film adaptation of Frank Herbert's novel.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Dune (2021)",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "First Harry Potter movie.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Harry Potter and the Sorcerer's Stone",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Horror film based on Stephen King's book.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Shining",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mind-bending thriller by Christopher Nolan.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Inception",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sequel to Batman Begins.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Dark Knight",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adaptation of Agatha Christie's mystery.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Murder on the Orient Express (2017)",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sci-fi epic by Christopher Nolan.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Interstellar",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Groundbreaking action sci-fi film.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Matrix",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adventure film with dinosaurs.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Jurassic Park",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic crime drama.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Godfather",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quentin Tarantino's nonlinear crime film.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Pulp Fiction",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Psychological thriller.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Fight Club",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heartwarming drama.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Forrest Gump",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prison drama based on Stephen King story.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Shawshank Redemption",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sequel to A New Hope.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Empire Strikes Back",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sci-fi novel by Frank Herbert (crossover with movie).",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Dune",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "First Harry Potter book (crossover with movie).",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Harry Potter and the Sorcerer's Stone",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Horror novel by Stephen King (crossover with movie).",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Shining",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mystery novel by Agatha Christie (crossover with movie).",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Murder on the Orient Express",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Horror novel by Stephen King.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "It",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fantasy prequel to Lord of the Rings.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Hobbit",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dystopian classic by George Orwell.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "1984",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic novel by Harper Lee.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "To Kill a Mockingbird",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "F. Scott Fitzgerald's jazz age novel.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Great Gatsby",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jane Austen's romantic classic.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Pride and Prejudice",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "J.D. Salinger's coming-of-age story.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Catcher in the Rye",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aldous Huxley's dystopian vision.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Brave New World",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dan Brown's thriller.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Da Vinci Code",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gillian Flynn's psychological thriller.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Gone Girl",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Suzanne Collins' dystopian adventure.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Hunger Games",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "MMORPG by Blizzard.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "World of Warcraft",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Open-world action game by Rockstar.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Grand Theft Auto V",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adventure game by Nintendo.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sandbox building game.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Minecraft",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Battle royale shooter.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Fortnite",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RPG based on Andrzej Sapkowski's books.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "The Witcher 3: Wild Hunt",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Team-based shooter by Blizzard.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Overwatch",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sci-fi RPG by CD Projekt Red.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Cyberpunk 2077",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historical action RPG.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Assassin's Creed Valhalla",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Platformer by Nintendo.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Super Mario Odyssey",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Collectible vinyl figure of Batman.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Funko Pop! Batman",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Collectible wand from the series.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Harry Potter Wand Replica",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Replica lightsaber.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Star Wars Lightsaber Toy",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "One Ring collectible.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Lord of the Rings Ring Replica",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            CreatedByUserId = "2fd28110-93d0-427d-9207-d55dbca680fa",
                            CreatedDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Collectible figure from Dune.",
                            IsActive = true,
                            IsOnSale = false,
                            Name = "Dune Sandworm Figure",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("EF10_InventoryModels.ItemContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<string>("ContributorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("ItemId", "ContributorId")
                        .IsUnique();

                    b.ToTable("ItemContributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributorId = 1,
                            ContributorType = "Actor",
                            ItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContributorId = 2,
                            ContributorType = "Actor",
                            ItemId = 1
                        },
                        new
                        {
                            Id = 3,
                            ContributorId = 3,
                            ContributorType = "Director",
                            ItemId = 1
                        },
                        new
                        {
                            Id = 4,
                            ContributorId = 4,
                            ContributorType = "Composer",
                            ItemId = 1
                        },
                        new
                        {
                            Id = 5,
                            ContributorId = 5,
                            ContributorType = "Author",
                            ItemId = 2
                        },
                        new
                        {
                            Id = 6,
                            ContributorId = 6,
                            ContributorType = "Publisher",
                            ItemId = 3
                        },
                        new
                        {
                            Id = 7,
                            ContributorId = 7,
                            ContributorType = "Manufacturer",
                            ItemId = 4
                        },
                        new
                        {
                            Id = 8,
                            ContributorId = 8,
                            ContributorType = "Actor",
                            ItemId = 5
                        },
                        new
                        {
                            Id = 9,
                            ContributorId = 9,
                            ContributorType = "Actor",
                            ItemId = 5
                        },
                        new
                        {
                            Id = 10,
                            ContributorId = 10,
                            ContributorType = "Director",
                            ItemId = 5
                        },
                        new
                        {
                            Id = 11,
                            ContributorId = 11,
                            ContributorType = "Composer",
                            ItemId = 5
                        },
                        new
                        {
                            Id = 12,
                            ContributorId = 12,
                            ContributorType = "Composer",
                            ItemId = 5
                        },
                        new
                        {
                            Id = 13,
                            ContributorId = 14,
                            ContributorType = "Director",
                            ItemId = 6
                        },
                        new
                        {
                            Id = 14,
                            ContributorId = 15,
                            ContributorType = "Actor",
                            ItemId = 6
                        },
                        new
                        {
                            Id = 15,
                            ContributorId = 16,
                            ContributorType = "Actor",
                            ItemId = 6
                        },
                        new
                        {
                            Id = 16,
                            ContributorId = 11,
                            ContributorType = "Composer",
                            ItemId = 6
                        },
                        new
                        {
                            Id = 17,
                            ContributorId = 19,
                            ContributorType = "Director",
                            ItemId = 7
                        },
                        new
                        {
                            Id = 18,
                            ContributorId = 18,
                            ContributorType = "Actor",
                            ItemId = 7
                        },
                        new
                        {
                            Id = 19,
                            ContributorId = 22,
                            ContributorType = "Director",
                            ItemId = 8
                        },
                        new
                        {
                            Id = 20,
                            ContributorId = 23,
                            ContributorType = "Actor",
                            ItemId = 8
                        },
                        new
                        {
                            Id = 21,
                            ContributorId = 10,
                            ContributorType = "Director",
                            ItemId = 9
                        },
                        new
                        {
                            Id = 22,
                            ContributorId = 11,
                            ContributorType = "Composer",
                            ItemId = 9
                        },
                        new
                        {
                            Id = 23,
                            ContributorId = 10,
                            ContributorType = "Director",
                            ItemId = 10
                        },
                        new
                        {
                            Id = 24,
                            ContributorId = 8,
                            ContributorType = "Actor",
                            ItemId = 10
                        },
                        new
                        {
                            Id = 25,
                            ContributorId = 11,
                            ContributorType = "Composer",
                            ItemId = 10
                        },
                        new
                        {
                            Id = 26,
                            ContributorId = 27,
                            ContributorType = "Director",
                            ItemId = 11
                        },
                        new
                        {
                            Id = 27,
                            ContributorId = 10,
                            ContributorType = "Director",
                            ItemId = 12
                        },
                        new
                        {
                            Id = 28,
                            ContributorId = 11,
                            ContributorType = "Composer",
                            ItemId = 12
                        },
                        new
                        {
                            Id = 29,
                            ContributorId = 3,
                            ContributorType = "Director",
                            ItemId = 13
                        },
                        new
                        {
                            Id = 30,
                            ContributorId = 4,
                            ContributorType = "Composer",
                            ItemId = 14
                        },
                        new
                        {
                            Id = 31,
                            ContributorId = 10,
                            ContributorType = "Director",
                            ItemId = 15
                        },
                        new
                        {
                            Id = 32,
                            ContributorId = 22,
                            ContributorType = "Director",
                            ItemId = 16
                        },
                        new
                        {
                            Id = 33,
                            ContributorId = 10,
                            ContributorType = "Director",
                            ItemId = 17
                        },
                        new
                        {
                            Id = 34,
                            ContributorId = 11,
                            ContributorType = "Composer",
                            ItemId = 18
                        },
                        new
                        {
                            Id = 35,
                            ContributorId = 21,
                            ContributorType = "Author",
                            ItemId = 19
                        },
                        new
                        {
                            Id = 36,
                            ContributorId = 1,
                            ContributorType = "Actor",
                            ItemId = 20
                        },
                        new
                        {
                            Id = 37,
                            ContributorId = 4,
                            ContributorType = "Composer",
                            ItemId = 20
                        },
                        new
                        {
                            Id = 38,
                            ContributorId = 13,
                            ContributorType = "Author",
                            ItemId = 21
                        },
                        new
                        {
                            Id = 39,
                            ContributorId = 17,
                            ContributorType = "Author",
                            ItemId = 22
                        },
                        new
                        {
                            Id = 40,
                            ContributorId = 21,
                            ContributorType = "Author",
                            ItemId = 23
                        },
                        new
                        {
                            Id = 41,
                            ContributorId = 26,
                            ContributorType = "Author",
                            ItemId = 24
                        },
                        new
                        {
                            Id = 42,
                            ContributorId = 21,
                            ContributorType = "Author",
                            ItemId = 25
                        },
                        new
                        {
                            Id = 43,
                            ContributorId = 5,
                            ContributorType = "Author",
                            ItemId = 26
                        },
                        new
                        {
                            Id = 44,
                            ContributorId = 13,
                            ContributorType = "Author",
                            ItemId = 27
                        },
                        new
                        {
                            Id = 45,
                            ContributorId = 26,
                            ContributorType = "Author",
                            ItemId = 28
                        },
                        new
                        {
                            Id = 46,
                            ContributorId = 5,
                            ContributorType = "Author",
                            ItemId = 29
                        },
                        new
                        {
                            Id = 47,
                            ContributorId = 17,
                            ContributorType = "Author",
                            ItemId = 30
                        },
                        new
                        {
                            Id = 48,
                            ContributorId = 21,
                            ContributorType = "Author",
                            ItemId = 31
                        },
                        new
                        {
                            Id = 49,
                            ContributorId = 13,
                            ContributorType = "Author",
                            ItemId = 32
                        },
                        new
                        {
                            Id = 50,
                            ContributorId = 26,
                            ContributorType = "Author",
                            ItemId = 33
                        },
                        new
                        {
                            Id = 51,
                            ContributorId = 21,
                            ContributorType = "Author",
                            ItemId = 34
                        },
                        new
                        {
                            Id = 52,
                            ContributorId = 17,
                            ContributorType = "Author",
                            ItemId = 35
                        },
                        new
                        {
                            Id = 53,
                            ContributorId = 20,
                            ContributorType = "Developer",
                            ItemId = 36
                        },
                        new
                        {
                            Id = 54,
                            ContributorId = 25,
                            ContributorType = "Developer",
                            ItemId = 37
                        },
                        new
                        {
                            Id = 55,
                            ContributorId = 20,
                            ContributorType = "Publisher",
                            ItemId = 38
                        },
                        new
                        {
                            Id = 56,
                            ContributorId = 6,
                            ContributorType = "Developer",
                            ItemId = 39
                        },
                        new
                        {
                            Id = 57,
                            ContributorId = 25,
                            ContributorType = "Developer",
                            ItemId = 40
                        },
                        new
                        {
                            Id = 58,
                            ContributorId = 20,
                            ContributorType = "Developer",
                            ItemId = 41
                        },
                        new
                        {
                            Id = 59,
                            ContributorId = 20,
                            ContributorType = "Developer",
                            ItemId = 42
                        },
                        new
                        {
                            Id = 60,
                            ContributorId = 25,
                            ContributorType = "Developer",
                            ItemId = 43
                        },
                        new
                        {
                            Id = 61,
                            ContributorId = 6,
                            ContributorType = "Publisher",
                            ItemId = 44
                        },
                        new
                        {
                            Id = 62,
                            ContributorId = 20,
                            ContributorType = "Developer",
                            ItemId = 45
                        },
                        new
                        {
                            Id = 63,
                            ContributorId = 24,
                            ContributorType = "Manufacturer",
                            ItemId = 46
                        },
                        new
                        {
                            Id = 64,
                            ContributorId = 7,
                            ContributorType = "Manufacturer",
                            ItemId = 47
                        },
                        new
                        {
                            Id = 65,
                            ContributorId = 24,
                            ContributorType = "Manufacturer",
                            ItemId = 48
                        },
                        new
                        {
                            Id = 66,
                            ContributorId = 7,
                            ContributorType = "Manufacturer",
                            ItemId = 49
                        },
                        new
                        {
                            Id = 67,
                            ContributorId = 24,
                            ContributorType = "Manufacturer",
                            ItemId = 50
                        });
                });

            modelBuilder.Entity("ItemGenres", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ItemGenres");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 1,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 2,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 2,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 3,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 4,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 5,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 5,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 5,
                            GenreId = 10
                        },
                        new
                        {
                            ItemId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 6,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            ItemId = 8,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 9,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 10,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 10,
                            GenreId = 10
                        },
                        new
                        {
                            ItemId = 10,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 11,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 11,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 12,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 13,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 13,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 14,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 14,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 15,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 15,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 16,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 16,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 17,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 17,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 18,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 18,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 19,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 19,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 20,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 20,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 21,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 21,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 21,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 22,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 22,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 23,
                            GenreId = 6
                        },
                        new
                        {
                            ItemId = 23,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 24,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 24,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 25,
                            GenreId = 6
                        },
                        new
                        {
                            ItemId = 26,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 26,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 27,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 27,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 28,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 28,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 29,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 29,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 30,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 30,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 31,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 31,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 32,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 32,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 33,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 33,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 34,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 34,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 35,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 35,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 36,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 36,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 37,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 37,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 38,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 38,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 39,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 40,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 41,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 41,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 42,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 42,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 43,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 43,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 44,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 44,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 45,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 46,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 46,
                            GenreId = 10
                        },
                        new
                        {
                            ItemId = 47,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 47,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 48,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 48,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 49,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 49,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 50,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 50,
                            GenreId = 1
                        });
                });

            modelBuilder.Entity("EF10_InventoryModels.Item", b =>
                {
                    b.HasOne("EF10_InventoryModels.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EF10_InventoryModels.ItemContributor", b =>
                {
                    b.HasOne("EF10_InventoryModels.Contributor", "Contributor")
                        .WithMany("ItemContributors")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF10_InventoryModels.Item", "Item")
                        .WithMany("ItemContributors")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ItemGenres", b =>
                {
                    b.HasOne("EF10_InventoryModels.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF10_InventoryModels.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF10_InventoryModels.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EF10_InventoryModels.Contributor", b =>
                {
                    b.Navigation("ItemContributors");
                });

            modelBuilder.Entity("EF10_InventoryModels.Item", b =>
                {
                    b.Navigation("ItemContributors");
                });
#pragma warning restore 612, 618
        }
    }
}
