name: Deploy IAC to Azure

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy-iac:
    runs-on: ubuntu-latest
    environment: 
        name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Deployment
        uses: azure/bicep-deploy@v2
        with:
            type: deployment
            operation: create
            name: deployinvmgr-${{ github.run_id }}
            location: centralus
            scope: subscription
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            template-file: ./iac/main.bicep
            parameters-file: ./iac/main.parameters.json

